# Generated by Django 4.2 on 2023-06-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_way', '0002_feedback_alter_deliciousway_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliciousway',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
